# Generated by Django 4.2.13 on 2024-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleType",
            fields=[
                ("sale_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
    ]
