# Generated by Django 4.2.14 on 2024-11-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="TestProduct",),
    ]
