# Generated by Django 4.2.13 on 2024-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0002_saletype"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_types",
            field=models.ManyToManyField(
                default=1, related_name="products", to="kalegooduapp.saletype"
            ),
        ),
    ]
