# Generated by Django 4.2.14 on 2024-08-05 14:00

from django.db import migrations, models
import kalegooduapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0003_product_discounted_price_product_sale_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "banner_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        upload_to=kalegooduapp.models.banner_image_upload_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
