# Generated by Django 4.2.14 on 2024-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0003_bannerimage_visible_category_visible_product_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="saletype",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
