# Generated by Django 4.2.14 on 2024-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0004_bannerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(default=0),
        ),
    ]
