# Generated by Django 4.2.14 on 2025-01-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0005_categoryimage_visible_customer_visible_order_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default='Add a note'),
        ),
    ]
