# Generated by Django 4.2.14 on 2025-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0006_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='send_promotion_emails',
            field=models.BooleanField(default=True),
        ),
    ]
