# Generated by Django 4.2.14 on 2025-01-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0008_category_banner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_category',
        ),
    ]
