# Generated by Django 4.2.14 on 2024-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0008_product_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="quantity", field=models.IntegerField(default=1),
        ),
    ]
