# Generated by Django 4.2.14 on 2025-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0009_remove_category_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='home_page',
            field=models.BooleanField(default=True),
        ),
    ]
