# Generated by Django 4.2.14 on 2024-08-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0009_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("phone_number", models.CharField(blank=True, max_length=12)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField()),
                ("pincode", models.CharField(max_length=6)),
            ],
        ),
    ]
