# Generated by Django 4.2.14 on 2024-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0010_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="id",),
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
