# Generated by Django 4.2.14 on 2025-02-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0011_subcategory_subcategoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(related_name='subcategories', to='kalegooduapp.category'),
        ),
    ]
