# Generated by Django 4.2.14 on 2025-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalegooduapp', '0012_remove_subcategory_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='kalegooduapp.subcategory'),
        ),
    ]
