# Generated by Django 4.2.14 on 2024-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0012_order_customer_created_at_customer_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="count", field=models.IntegerField(default=1),
        ),
    ]
