# Generated by Django 4.2.14 on 2024-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0016_pagecontent_pageimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="pagecontent", name="id",),
        migrations.RemoveField(model_name="pageimage", name="id",),
        migrations.AddField(
            model_name="pagecontent",
            name="pagecontent_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pageimage",
            name="pageimage_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
