# Generated by Django 4.2.14 on 2024-09-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0017_remove_pagecontent_id_remove_pageimage_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                ("workshop_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("place", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkshopVideo",
            fields=[
                (
                    "workshopvideo_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("video_url", models.URLField()),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="kalegooduapp.workshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkshopImage",
            fields=[
                (
                    "workshopimage_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("image", models.ImageField(upload_to="workshop_images/")),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="kalegooduapp.workshop",
                    ),
                ),
            ],
        ),
    ]
