# Generated by Django 4.2.14 on 2024-09-13 15:50

from django.db import migrations, models
import kalegooduapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0019_workshop_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=kalegooduapp.models.workshop_image_upload_path,
            ),
        ),
    ]
