# Generated by Django 4.2.14 on 2024-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0020_alter_workshopimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_completed",
            field=models.BooleanField(default=False),
        ),
    ]
