# Generated by Django 4.2.14 on 2024-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0022_comment_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
