# Generated by Django 4.2.14 on 2024-10-25 16:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalegooduapp", "0023_workshop_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestProduct",
            fields=[
                ("testproduct_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
        ),
    ]
